---
on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    env:
      SAM_CLI_TELEMETRY: 0
    concurrency: ${{ format('{0}-{1}', github.event.repository.name, github.event_name == 'push' && github.ref_name || format('pr-{0}', github.event.number)) }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::412654396766:role/GitHubActions-Deploy
      - run: >
          sam delete
          --stack-name ${{ github.event.repository.name }}-pr-${{ github.event.number }}
          --no-prompts