on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy:
    strategy:
      matrix:
        env: ${{ fromJson(github.event_name == 'push' && '["staging","production"]' || '["staging"]') }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    env:
      AWS_REGION: eu-central-1
      SAM_CLI_TELEMETRY: 0
      STACK_NAME: ${{ format('{0}-{1}', github.event.repository.name, github.event_name == 'push' && github.ref_name || format('pr-{0}', github.event.number)) }}
      S3_BUCKET: ${{ format('samclisourcebucket-github.com-{0}-{1}-{2}', github.repository.owner.name, github.repository.name, matrix.env) }}
    concurrency: ${{ github.event_name == 'push' && matrix.env || github.event.number }}
    environment: ${{ matrix.env }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION  }}
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      # ── SAM build + deploy ──────────────────────────────────────────────
      - run: >
          aws s3api create-bucket 
          --bucket "$S3_BUCKET"
          --create-bucket-configuration LocationConstraint="$AWS_REGION"
          || echo "BucketAlreadyOwnedByYou is fine"
      - run: >
          sam build
          --parallel
      - run: >
          sam deploy
          --stack-name "$STACK_NAME"
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --s3-bucket "$S3_BUCKET"
          --s3-prefix "$STACK_NAME/$GITHUB_SHA"
          --capabilities CAPABILITY_IAM
      - run: aws cloudformation describe-stacks --stack-name "$STACK_NAME" > stack.json
      - run: jq -r '.' stack.json
      - run: jq -r '.Stacks[0].Outputs[] | "\(.OutputKey)=\(.OutputValue)"' stack.json >> "$GITHUB_OUTPUT"
        id: cf_outputs
      - run: aws s3 sync web/ "s3://$BUCKET_NAME/"
        env:
          BUCKET_NAME: ${{ steps.cf_outputs.outputs.WebsiteBucketName }}
      - run: >
          aws cloudfront create-invalidation
          --distribution-id "$DISTRIBUTION_ID"
          --paths "/*"
        env:
          DISTRIBUTION_ID: ${{ steps.cf_outputs.outputs.CloudFrontDistributionId }}
      - if: github.event_name == 'pull_request'
        run: gh pr comment "$PR_NUMBER" --edit-last --create-if-none --body "$CLOUDFRONT_URL"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          CLOUDFRONT_URL: ${{ steps.cf_outputs.outputs.CloudFrontURL }}